### ISSUE TITLE
音画不同步

### ISSUE THREAD

**Issue by EricNie2003** [HMBSbige/BilibiliLiveRecordDownLoader#126]
flv时间戳有误（可能是因为录制过程中卡了一下），转封装后的mp4出现音画不同步现象，视频播放速度比音频更快

**Comment by EricNie2003** [comment]
emm，转封装的时候把修复时间戳去掉之后就没事了，这是修复时间戳功能有bug吗

**Comment by HMBSbige** [comment]
应该是预期行为，毕竟本来传来的 flv 格式就很乱
