### ISSUE TITLE
经常会出现UI错位情况

### ISSUE THREAD

**Issue by 594854527** [HMBSbige/BilibiliLiveRecordDownLoader#137]
![屏幕截图 2021-08-24 003431](https://user-images.githubusercontent.com/63969532/130484553-9a3a9074-ad64-4bd2-a979-dd5d573dc529.png)
还有就是按钮消失等情况

**Comment by HMBSbige** [comment]
尝试 Win64 的版本，这种往往都是系统少文件导致的
