### ISSUE TITLE
录播机需求汇总

### ISSUE THREAD

**Issue by HMBSbige** [HMBSbige/BilibiliLiveRecordDownLoader#2]
* [x] 录制开关控制
* [x] 直播间标题变化记录
* [x] 通知开播提醒
* [x] 速度监控
* [x] 画质选择
* [x] 弹幕服务器类型选择
	- [x] 实测时间长了弹幕服务器响应慢，~~原因未知~~ Pipeline 处理错误 (5c937a946477cee57e9ae3c202dcb599e4a456eb)
* [x] 录制完成自动转 mp4
* [x] 登录
	- [x] 扫码登陆
	- [x] 登录成功后弹幕鉴权需修改(uid)，否则 ws 的弹幕会被断开
* [x] 简单剪辑
* [x] 手动转 mp4
* [x] 使用 系统代理/不使用代理

其他功能
* [x] 开机自启动

**Comment by HMBSbige** [comment]
如有人能提供[原项目](https://github.com/HMBSbige/AutoSplitVideo)中 **未启用** 时间戳修复 功能，转`mp4`封装后时间轴还是不正确的录制档就好了

**Comment by Skimige** [comment]
画质选择这个顺带提一下，S10 期间 B 站有个 4K 直播间，对应 qn 是 800，这档（4K）故意放在了原画的下面（而原画是 1080p）
不知道后面会不会再次出现（

**Comment by HMBSbige** [comment]
> 画质选择这个顺带提一下，S10 期间 B 站有个 4K 直播间，对应 qn 是 800，这档（4K）故意放在了原画的下面（而原画是 1080p）
> 不知道后面会不会再次出现（

@Skimige 这个我是知道的，现在 api 也能获取到

4K 不一定比原画画质就高，所以想搞个自行选择，就是不知道该怎么设计（简单点直接手动设置 qn 参数？）

**Comment by dunkirk-4** [comment]
不同的qn对应什么样的画质呢？？？

**Comment by HMBSbige** [comment]
qn|描述
-|-
10000|原画
800|4K
401|蓝光(杜比)
400|蓝光
250|超清
150|高清
80|流畅

**Comment by HMBSbige** [comment]
当然直播间没有的画质肯定请求不到

**Comment by LzNOHentai** [comment]
现在手动选择画质的录制逻辑是什么？比如如果选了4K，但实际没有这个画质，那自动录制原画？

关于画质能否做一个自动判断的选项？因为只想录制最高画质，但一些活动直播开播前并不清楚是否会提供4K画质。
比如如果提供4K，且原画是1080P，那么自动录制4K。以及同分辨率情况下自动录制高码率的流。
不过不太清楚会不会出现4K和原画都是4K分辨率但码率不同的情况，如果有这种情况不知道能否自动录制码率or帧率更高的画质。

**Comment by HMBSbige** [comment]
> 现在手动选择画质的录制逻辑是什么？比如如果选了4K，但实际没有这个画质，那自动录制原画？
> 
> 关于画质能否做一个自动判断的选项？因为只想录制最高画质，但一些活动直播开播前并不清楚是否会提供4K画质。
> 比如如果提供4K，且原画是1080P，那么自动录制4K。以及同分辨率情况下自动录制高码率的流。
> 不过不太清楚会不会出现4K和原画都是4K分辨率但码率不同的情况，如果有这种情况不知道能否自动录制码率or帧率更高的画质。

现在只是请求的画质，具体返回什么画质由 B 站决定

这种自动判断码率/帧率的逻辑很复杂，你还得一个个请求后手动分析视频...

**Comment by LzNOHentai** [comment]
> > 现在手动选择画质的录制逻辑是什么？比如如果选了4K，但实际没有这个画质，那自动录制原画？
> > 关于画质能否做一个自动判断的选项？因为只想录制最高画质，但一些活动直播开播前并不清楚是否会提供4K画质。
> > 比如如果提供4K，且原画是1080P，那么自动录制4K。以及同分辨率情况下自动录制高码率的流。
> > 不过不太清楚会不会出现4K和原画都是4K分辨率但码率不同的情况，如果有这种情况不知道能否自动录制码率or帧率更高的画质。
> 
> 现在只是请求的画质，具体返回什么画质由 B 站决定
> 
> 这种自动判断码率/帧率的逻辑很复杂，你还得一个个请求后手动分析视频...

好吧
顺带一提，现在4K的qn似乎是20000。

**Comment by HMBSbige** [comment]
> > > 现在手动选择画质的录制逻辑是什么？比如如果选了4K，但实际没有这个画质，那自动录制原画？
> > > 关于画质能否做一个自动判断的选项？因为只想录制最高画质，但一些活动直播开播前并不清楚是否会提供4K画质。
> > > 比如如果提供4K，且原画是1080P，那么自动录制4K。以及同分辨率情况下自动录制高码率的流。
> > > 不过不太清楚会不会出现4K和原画都是4K分辨率但码率不同的情况，如果有这种情况不知道能否自动录制码率or帧率更高的画质。
> > 
> > 
> > 现在只是请求的画质，具体返回什么画质由 B 站决定
> > 这种自动判断码率/帧率的逻辑很复杂，你还得一个个请求后手动分析视频...
> 
> 好吧。可不可以直接用网页播放器右键信息里的码率大小简单粗暴判断？那个的信息是分析视频本身得出的吗？还是服务器直接给？
> 顺带一提，现在4K的qn似乎是20000。

感谢反馈，已更新 Qn 硬编码

网页里的其实就是当前源，你当然要一个个去请求才可能知道全部的数据

获取到视频前是不知道源数据是怎么样的，甚至有 `4K` 比 `原画` 的画质低的
