### ISSUE TITLE
希望可以增加暂停录制和继续录制的开关

### ISSUE THREAD

**Issue by fgb766211** [HMBSbige/BilibiliLiveRecordDownLoader#20]

**Comment by HMBSbige** [comment]
啊？

![image](https://user-images.githubusercontent.com/19153265/103150433-23c69d80-47af-11eb-83dd-8b97d52fde41.png)

这难道不是吗？

**Comment by fgb766211** [comment]
> 啊？
> 
> ![图片](https://user-images.githubusercontent.com/19153265/103150433-23c69d80-47af-11eb-83dd-8b97d52fde41.png)
> 
> 这难道不是吗？



> 啊？
> 
> ![图片](https://user-images.githubusercontent.com/19153265/103150433-23c69d80-47af-11eb-83dd-8b97d52fde41.png)
> 
> 这难道不是吗？

完了，我这眼睛没救了，找了半天没找到TAT
