### ISSUE TITLE
转封装

### ISSUE THREAD

**Issue by Aoki-Sakura** [HMBSbige/BilibiliLiveRecordDownLoader#233]
录播姬自带的转封装有问题，转出来的视频我导入到pr会丢帧跳帧，拿flv文件用obs转封装就没有这个问题
FFmpeg状态
版本:5.0-essentials_build-www.gyan.dev
![image](https://user-images.githubusercontent.com/106068053/169785518-5087463a-ec8c-45a2-9aff-74c030e46bf7.png)

**Comment by HMBSbige** [comment]
修复时间戳开了吗？
开关都可以试试，其实就是两种不同的转封装方法

**Comment by Aoki-Sakura** [comment]
ok十分感谢，之前开了修复时间戳，关了就没问题了
