### ISSUE TITLE
主播开播之后，等待开始录制时间过长。

### ISSUE THREAD

**Issue by wardhardack** [HMBSbige/BilibiliLiveRecordDownLoader#282]
软件用了一周。主播开播检测到之后，录制状态显示橙色准备录制时间，不录制视频，直到我把直播间删除，重新启动软件再添加直播间才能开始录制。
软件是什么问题。
还有没录到跳舞区的烧鸡直播，我好急

**Comment by HMBSbige** [comment]
一般是自己网络问题呢

**Comment by hechuan4** [comment]
有哪些直播间？分享一下房间号
