### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by HMBSbige** [HMBSbige/BilibiliLiveRecordDownLoader#312]
### Discussed in https://github.com/HMBSbige/BilibiliLiveRecordDownLoader/discussions/311

<div type='discussions-op-text'>

<sup>Originally posted by **yuika1103** December 19, 2023</sup>
3.14.3.0版本，验证登录没有框跳出来，扫描二维码登录扫了也没反应。</div>

**Comment by yuika1103** [comment]
在别的地方看到有人碰到了同样的问题，用这个方法解决了：
用浏览器登B站，F12看网络/Network里请求接口的请求标头，里面的cookie复制到这个软件扫描二维码上面的Cookie里，点一下验证登录就行了

**Comment by HMBSbige** [comment]
> 在别的地方看到有人碰到了同样的问题，用这个方法解决了： 用浏览器登B站，F12看网络/Network里请求接口的请求标头，里面的cookie复制到这个软件扫描二维码上面的Cookie里，点一下验证登录就行了

workaround 确实可以这样，但是本质还是B站又改了扫码登录的接口
