### ISSUE TITLE
关于录制的问题

### ISSUE THREAD

**Issue by yuna4747** [HMBSbige/BilibiliLiveRecordDownLoader#335]
想问一下，在录制5265这个直播间的时候，录制状态一直处于启动中，直到直播结束之后都不会是启动中的状态，尝试录制过其他直播间，录制功能是正常状态，中间卸载过几次，安装其他版本也是一样的问题，想问一下有没有办法解决（目前的版本号是3.15.2）
![PixPin_2024-07-31_20-47-19](https://github.com/user-attachments/assets/4ee4b014-61e6-45cf-8a4b-6e3dd75e3590)

**Comment by HMBSbige** [comment]
至少也要提供一下日志吧

**Comment by yuna4747** [comment]
> 至少也要提供一下日志吧

早些时候重新下载安装日志清空了，等后续又有直播了我再发日志
