### ISSUE TITLE
能否添加下载弹幕功能呢？

### ISSUE THREAD

**Issue by j6189802** [HMBSbige/BilibiliLiveRecordDownLoader#4]
下载回放起来方便多了，帮大忙了

如果弹幕也能下载就更好了

**Comment by HMBSbige** [comment]
直播回放的弹幕我没找到直接下的地址，跟录播一样的是用 websocket 发送的

**Comment by BlueskyClouds** [comment]
弹幕目前貌似是没有直接的下载地址的，需要手动记录保存

**Comment by HMBSbige** [comment]
* 获取直播回放弹幕信息
`https://api.live.bilibili.com/xlive/web-room/v1/record/getInfoByLiveRecord?rid={Rid}`
* 按页数获取直播回放弹幕
`https://api.live.bilibili.com/xlive/web-room/v1/dM/getDMMsgByPlayBackID?rid={Rid}&index=0`

不知道怎么 Parse，也没这个需求，留给后面的人做~~咕咕咕~~

**Comment by Sodapopoo** [comment]
这个功能真的没法做吗，过5个月了也没有进展，毕竟没弹幕就没有互动感啊……能教教我怎么扒直播回放的弹幕吗？

**Comment by HMBSbige** [comment]
> 这个功能真的没法做吗，过5个月了也没有进展，毕竟没弹幕就没有互动感啊……能教教我怎么扒直播回放的弹幕吗？

你想要的东西肯付钱就能拥有.gif

**Comment by Sodapopoo** [comment]
> 你想要的东西肯付钱能够拥有.gif

请问，可以付钱请你开发这个功能吗？

**Comment by HMBSbige** [comment]
@Sodapopoo https://t.me/HMBSbige
