### ISSUE TITLE
ip被412后降低刷新频率

### ISSUE THREAD

**Issue by shoucandanghehe** [HMBSbige/BilibiliLiveRecordDownLoader#52]
B站风控412后录播机还会持续以设定的频率请求直播间状态
导致风控状态短时间不能解除
可以在412后将开播检查时间延长一定时间，比如一分钟检查一次
（应该不会有人用默认的300s吧

**Comment by HMBSbige** [comment]
典型的不懂参数乱改，改那么短被 412 不是很正常吗？

直播间状态由弹幕获取，只要与弹幕服务器的连接不断就可以做到零延迟获取，手动刷新只是辅助手段
